//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.21 at 12:19:14 AM CEST 
//


package JAXB_Files;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the JAXB_Files package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Estacion_QNAME = new QName("https://api.mobipalma.mobi/docs/", "estacion");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: JAXB_Files
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TypeEstacion }
     * 
     */
    public TypeEstacion createTypeEstacion() {
        return new TypeEstacion();
    }

    /**
     * Create an instance of {@link TypeAnclajes }
     * 
     */
    public TypeAnclajes createTypeAnclajes() {
        return new TypeAnclajes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeEstacion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://api.mobipalma.mobi/docs/", name = "estacion")
    public JAXBElement<TypeEstacion> createEstacion(TypeEstacion value) {
        return new JAXBElement<TypeEstacion>(_Estacion_QNAME, TypeEstacion.class, null, value);
    }

}
