//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.21 at 12:19:14 AM CEST 
//


package JAXB_Files;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeEstacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeEstacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{https://api.mobipalma.mobi/docs/}typeId"/>
 *         &lt;element name="direccion" type="{https://api.mobipalma.mobi/docs/}typeDireccion"/>
 *         &lt;element name="numeroAnclajes" type="{https://api.mobipalma.mobi/docs/}typeNumeroAnclajes"/>
 *         &lt;element name="anclajes" type="{https://api.mobipalma.mobi/docs/}typeAnclajes"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeEstacion", propOrder = {
    "id",
    "direccion",
    "numeroAnclajes",
    "anclajes"
})
public class TypeEstacion {

    protected int id;
    protected int direccion;
    protected int numeroAnclajes;
    @XmlElement(required = true)
    protected TypeAnclajes anclajes;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the direccion property.
     * 
     */
    public int getDireccion() {
        return direccion;
    }

    /**
     * Sets the value of the direccion property.
     * 
     */
    public void setDireccion(int value) {
        this.direccion = value;
    }

    /**
     * Gets the value of the numeroAnclajes property.
     * 
     */
    public int getNumeroAnclajes() {
        return numeroAnclajes;
    }

    /**
     * Sets the value of the numeroAnclajes property.
     * 
     */
    public void setNumeroAnclajes(int value) {
        this.numeroAnclajes = value;
    }

    /**
     * Gets the value of the anclajes property.
     * 
     * @return
     *     possible object is
     *     {@link TypeAnclajes }
     *     
     */
    public TypeAnclajes getAnclajes() {
        return anclajes;
    }

    /**
     * Sets the value of the anclajes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeAnclajes }
     *     
     */
    public void setAnclajes(TypeAnclajes value) {
        this.anclajes = value;
    }

}
